apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-client
  namespace: fastapi-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      containers:
        - name: streamlit
          image: mohammedkhubaib/streamlit-client:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: API_BASE_URL
              value: "http://fastapi:8000"
          ports:
            - containerPort: 8501
---
apiVersion: v1
kind: Service
metadata:
  name: streamlit
  namespace: fastapi-app
spec:
  type: NodePort
  selector:
    app: streamlit
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
      nodePort: 30002
