apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: fastapi-app
type: Opaque
data:
  # postgres (base64 encoded)
  POSTGRES_USER: postgres
  # postgres (base64 encoded)
  POSTGRES_PASSWORD: postgres
  # postgres (base64 encoded)
  POSTGRES_DB: postgres