version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5434:5432"
    networks:
      - fastapi-network

  api:
    image: mohammedkhubaib/fastapi-server:latest       # Use the pre-built image
    ports:
      - "8000:8000"
    # env_file:
      # - .env
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db/postgres"
    depends_on:
      - db
    networks:
      - fastapi-network
  
  client:
    image: mohammedkhubaib/streamlit-client:latest     # Use the pre-built image
    ports:
      - "8501:8501"
    depends_on:
      - api
    environment:
      # If your client needs API URL
      API_BASE_URL: "http://api:8000"
    networks:
      - fastapi-network

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "True"
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - fastapi-network

networks:
  fastapi-network: