apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-api
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app: fastapi-api
  template:
    metadata:
      labels:
        app: fastapi-api
    spec:
      containers:
      - name: fastapi-api
        image: {{ .Values.api.image }}
        ports:
        - containerPort: {{ .Values.api.service.port }}
        env:
        - name: DATABASE_URL
          value: "postgresql://{{ .Values.postgres.user }}:{{ .Values.postgres.password }}@postgres-service:{{ .Values.postgres.service.port }}/{{ .Values.postgres.database }}"