apiVersion: v1
kind: Service
metadata:
  name: fastapi-api-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: fastapi-api
  ports:
  - port: {{ .Values.api.service.port }}
    targetPort: {{ .Values.api.service.port }}
    nodePort: {{ .Values.api.service.nodePort }}
  type: NodePort