apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: pgadmin
  ports:
  - port: {{ .Values.pgadmin.service.port }}
    targetPort: 80
    nodePort: {{ .Values.pgadmin.service.nodePort }}
  type: NodePort