apiVersion: v1
kind: Service
metadata:
  name: streamlit-client-service
  namespace: fastapi-app
spec:
  selector:
    app: streamlit-client
  ports:
  - port: 8501
    targetPort: 8501
    nodePort: 30001
  type: NodePort