apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  namespace: fastapi-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
      - name: pgadmin
        image: dpage/pgadmin4:latest
        ports:
        - containerPort: 80
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          valueFrom:
            configMapKeyRef:
              name: pgadmin-config
              key: PGADMIN_DEFAULT_EMAIL
        - name: PGADMIN_DEFAULT_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: pgadmin-config
              key: PGADMIN_DEFAULT_PASSWORD
        - name: PGADMIN_CONFIG_SERVER_MODE
          valueFrom:
            configMapKeyRef:
              name: pgadmin-config
              key: PGADMIN_CONFIG_SERVER_MODE
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      initContainers:
      - name: wait-for-postgres
        image: busybox:1.35
        command: ['sh', '-c', 'until nc -z postgres-service 5432; do sleep 1; done']