apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
  namespace: fastapi-app
spec:
  selector:
    app: pgadmin
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30002
  type: NodePort