apiVersion: v1
kind: Service
metadata:
  name: fastapi-api-service
  namespace: fastapi-app
spec:
  selector:
    app: fastapi-api
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30000
  type: NodePort