apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-client
  namespace: fastapi-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit-client
  template:
    metadata:
      labels:
        app: streamlit-client
    spec:
      containers:
      - name: streamlit-client
        image: mohammedkhubaib/streamlit-client:latest
        ports:
        - containerPort: 8501
        env:
        - name: API_BASE_URL
          value: "http://fastapi-api-service:8000"